// Blur placeholder data URLs for hero and key images
export const blurDataURLs = {
  heroPhoto: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAADCAIAAAA7ljmRAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAMElEQVR4nGOo7e8/dvbM3///P3x4z2BmpZJblLJkyYzu1kIGQyUGF2s+HU0OQWYGAKKoEE44jvtDAAAAAElFTkSuQmCC',
  profilePhoto: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAMAAAAECAIAAADETxJQAAAACXBIWXMAADXUAAA11AFeZeUIAAAAMUlEQVR4nGP4+PXZ7///n7y4wtA2060qx6+oQ5mhtanAVV+rrTWXIdbNRoKBoyw+GgDExxHYWfenEAAAAABJRU5ErkJggg==',
  emCover: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAACCAYAAAB/qH1jAAAACXBIWXMAAAsTAAALEwEAmpwYAAAALUlEQVR4nAEiAN3/AFNGPf87Mir/19fb/+Pj4/8AXE9G/xYBAP+MjY7/ubm5/zqAE3K4zldpAAAAAElFTkSuQmCC',
  sdCover: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAACCAIAAADwyuo0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAI0lEQVR4nGNgYOXyTS+qmL+hdMpMhk1798Y2TevZd/vE//8AhJgNK+rNlUkAAAAASUVORK5CYII=',
};
